## **Inputs & Outputs**

Inputs
*   Data atau nilai yang diberikan kepada sebuah program.
*   Dapat dimasukkan oleh user, dibaca dari sebuah file, atau diperoleh dari sumber lain.

Outputs
*   Hasil atau informasi yang dihasilkan oleh program.
*   Dapat ditampilkan di layar, ditulis ke file, atau dikirim ke sistem lain.
*   Mewakili hasil akhir program dan menyediakan pengguna atau program lain dengan informasi atau hasil yang diinginkan.





In [2]:
# Contoh dari User
# Menerima Input dari User
name = input('Masukkan nama anda: ')

# Mengeluarkan Output ditampilkan ke layar
print('Halo, ' + name + '! Selamat Belajar Python!')

Masukkan nama anda: Afin
Halo, Afin! Selamat Belajar Python!


In [3]:
# Contoh dari File
lokasi_file = '/content/sample_data/baca_file.txt'
with open(lokasi_file, 'r') as file:
  file_content = file.read()
  print("Isi dari file adalah:", file_content)

Isi dari file adalah: Selamat! Anda berhasil membaca input dari file


In [4]:
# Contoh menulis output dalam file
output_data = "Kita ingin menulis kedalam file"
lokasi_file_output = '/content/sample_data/output_file.txt'

with open(lokasi_file_output, 'w') as output_file:
  output_file.write(output_data)

Catatan
*   Tipe data input dari user dengan *function* input() adalah string atau str.
*   Jika ingin user untuk menginput contohnya bilangan bulat, maka kita harus melakukan konversi terhadap data input tersebut.


In [5]:
umur = input('Berapa umur anda:')
print(type(umur))

Berapa umur anda:21
<class 'str'>


In [6]:
# Untuk memastikan menjadi bilangan bulat, maka berikan konversi data diluar input
umur = int(input('Berapa umur anda:'))
print(type(umur))

Berapa umur anda:21
<class 'int'>


### **Loop**

Pernahkah?
*   Mendengarkan lagu favorit berulang-ulang.
*   Pergi ke kantor atau kampus menempuh rute yang sama setiap hari.
*   Berulang kali menunggu hari gajian, tetapi ketika sudah gajian cuma numpang lewat doang.

Dalam pemrograman, fenomena di atas bisa dikerjakan karena adanya *iteration* atau *loop*.




Loop digunakan untuk mengulangi urutan (yaitu list, tuple, dictionary, set, atau string)

Python memiliki dua perintah loop yang umum:
*   While loop
    indefinite iteration - pengulangan sampai suatu syarat terpenuhi
*   For loop
    definite iteration - pengulangan dengan jumlah pengulangan yang didefinisikan terlebih dahulu


In [8]:
# Mengeksekusi satu set pernyataan selama kondisinya benar
i = 1
while i < 6:
  print(i)
  i += 1

# Catatan: ingat untuk menambah/mengurangi variable sesuai kondisi, atau loop akan berlanjut selamanya

1
2
3
4
5


### **FOR LOOP**

In [9]:
# membuat iterator untuk mengeksekusi perintah dari satu set list, tuple, set, range, dll.
# eksekusi sebanyak satu kali

for x in "banana":
  print(x)

b
a
n
a
n
a


In [10]:
for x in range(1,6):
  print(x)

1
2
3
4
5


In [ ]:
range(akhir) # start from 0 end at akhir -1
range(awal, akhir) # start from awal, end at akhir
range(awal, akhir, jarak) # start from awal, end at akhir, at interval = jarak

In [18]:
for x in range(1,10,2): #range(awal, akhir, jarak)
  print(x)

1
3
5
7
9


In [11]:
list_buah = ['apel', 'pisang', 'melon', 'durian']
for buah in list_buah:
  print(buah)

apel
pisang
melon
durian


### **NESTED LOOP**

In [12]:
# Loop yang ada didalam loop
# Program menyelesaikan loop terdalam dahulu lalu melanjutkan loop terluar

for x in "banana":

  for y in range(6):
    print(x, end = " ")

  print("")

print("end of code")

b b b b b b 
a a a a a a 
n n n n n n 
a a a a a a 
n n n n n n 
a a a a a a 
end of code


In [13]:
for i in range(5): # I dari 0 s/d 4
  for j in ['a', 'b', 'c']: # J akan mengakses setiap value dalam list
    print(i,j)

0 a
0 b
0 c
1 a
1 b
1 c
2 a
2 b
2 c
3 a
3 b
3 c
4 a
4 b
4 c


In [14]:
for i in range(1,11):
  for j in range(1,11):
    print(i*j, end=' ')
  print()

1 2 3 4 5 6 7 8 9 10 
2 4 6 8 10 12 14 16 18 20 
3 6 9 12 15 18 21 24 27 30 
4 8 12 16 20 24 28 32 36 40 
5 10 15 20 25 30 35 40 45 50 
6 12 18 24 30 36 42 48 54 60 
7 14 21 28 35 42 49 56 63 70 
8 16 24 32 40 48 56 64 72 80 
9 18 27 36 45 54 63 72 81 90 
10 20 30 40 50 60 70 80 90 100 


### **Fungsi Control**

Kegunaan = mengontrol jalannya loop (memberi perintah berhenti, lanjutkan, atau abaikan)

Fungsi Control = Break, Continue, Pass

In [15]:
# Break
# berfungsi memberhentikan proses loop

for x in range(1,6):
  if (x==3):
    break
  else:
    print(x)

1
2


In [16]:
# Continue
# berfungsi memberhentikan proses saat ini kemudian melanjutkannya kembali di loop selanjutnya
# jika dikombinasikan dengan fungsi kondisi if bisa digunakan untuk melewatkan 1 putaran loop

for x in range(1,6):
  if (x==3):
    continue
  else:
    print(x)

1
2
4
5


In [17]:
# Pass
# fungsi loop tidak boleh kosong
# jika karena alasan tertentu kita harus memiliki for loop tanpa konten, memasukkan pernyataan pass untuk menghindari kesalahan

for x in range(1,6):
  pass

### **Quiz 1 Advance Python Foundation**

In [19]:
for i in range(2, 8, 2):
  print(i)

2
4
6


### **Flowchart**

*   Representasi grafis algoritma yang digunakan oleh programmer sebagai alat perencanaan program.
*   Simbol-simbolnya saling terhubung untuk menunjukkan alur informasi dan pemrosesan.
*   Proses pembuatan flowchart disebut *flowcharting*.




### **Functional Programming**

Fungsi dalam istilah matematika merupakan pemetaan setiap anggota sebuah himpunan kepada anggota himpunan yang lain.
Langkah-langkah yang memiliki:
*   masukan
*   urutan proses, dan
*   keluaran.




***Functional programming*** adalah paradigma pemrograman yang berkutat pada komputasi yang terjadi di dalam fungsi matematis dan menghindari terjadinya perubahan data.
Keunggulan Pemrograman Fungsional:
*   Menggunakan fungsi dapat **menyederhanakan kode**.
*   **Memisahkan setiap alur kerja** sesuai fungsinya. Contohnya, bersihkan data, panggil data dari csv, dll.
*   Memudahkan kita untuk **fokus pada pemecahan masalah**, daripada men-debug proses yang sama berulang kali.
*   Setiap masalah atau kesalahan **mudah dilacak**.



In [22]:
# Struktur Fungsi dalam Python

def wealth_estimator(money):    # def   nama fungsi   variable fungsi

  if money>=1000000:  # proses dan instruksi program
    status="You are above 1%"

  elif money<1000000 and money<=100: # proses dan instruksi program
    status="You are in middle class"

  else: # proses dan instruksi program
    status="You are poor"

  return status # output return

### **Global & Local Variable**

In [24]:
# Global Variable
x = 'keren!'
def fungsi1():
  print('Python itu' + x)

fungsi1()

Python itukeren!


In [25]:
print(x)

keren!


In [27]:
# Local Variable
def fungsi2():
  nama = ' Agus '
  print('Nama saya' + nama)

fungsi2()

Nama saya Agus 


In [28]:
print(nama) # Variable tidak berfungsi karena hanya berfungsi pada fungsi2 pada local variable

NameError: name 'nama' is not defined

In [29]:
def luas_persegi(sisi):
  luas = sisi * sisi
  return luas

In [31]:
persegi1 = luas_persegi(5)
print(persegi1)

25


### **Quiz 2 Advance Python Foundation From Startup Campus**

In [32]:
numbers = [1, 2, 3, 4, 5]
def square(x):
  return x**2
squared_numbers = [square(num) for num in numbers]
print(squared_numbers)

[1, 4, 9, 16, 25]


### **Array & NumPy Library**

Library adalah kode eksternal yang dapat diimpor ke dalam project kita.
Library adalah kumpulan kode yang dibuat oleh seseorang, komunitas, atau perusahaan.

NumPy (Numerical Python) adalah library yang ada di Python dan digunakan untuk membuat array. Dibuat pada tahun 2005 oleh Travis Oliphant.

Keuntungan:
*   Lebih cepat dari List yang ada di Python.
*   Menggunakan lebih sedikit memori untuk menyimpan data
*   Bisa digunakan untuk membuat array n-dimensi
*   Bisa melakukan operasi matematika pada array n-dimensi





In [1]:
# Menginstall numpy

!pip install numpy

In [7]:
# Mengimport numpy

import numpy
numpy.__version__

'1.26.4'

In [8]:
# Mengimport numpy sebagai inisial

import numpy as np
np.__version__

'1.26.4'

### Membuat Array dengan Numpy

*   Objek array di NumPy disebut ndarray.
*   Kita dapat membuat objek ndarray NumPy dengan menggunakan fungsi array().
*   Dimensi dalam array adalah tingkat kedalaman array.



In [9]:
# 1-D Array
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print('Jumlah Dimensi :', arr.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
Jumlah Dimensi : 1


In [14]:
# 2-D Array
arr = np.array([[1,2,3], [4,5,6]])
print(arr)
print(type(arr))
print('Jumlah Dimensi :', arr.ndim)
print('Shape Array :', arr.shape)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
Jumlah Dimensi : 2
Shape Array : (2, 3)


In [17]:
# 3-D Array
arr = np.array([[[1,2,3],[4,5,6]],
                [[2,4,6],[8,10,12]]])
print(arr)
print(type(arr))
print('Jumlah Dimensi :', arr.ndim)
print('Shape Array :', arr.shape) # (Depth/Layer, Baris, Kolom)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 2  4  6]
  [ 8 10 12]]]
<class 'numpy.ndarray'>
Jumlah Dimensi : 3
Shape Array : (2, 2, 3)


### **Quiz 3 Advance Python Foundation From Startup Campus**

In [20]:
import numpy as np

original_array = np.array([1,2,3,4,5])
squared_array = np.square(original_array)
added_array = squared_array + 10
subset_array = added_array[1:4]

print(subset_array)

[14 19 26]
